### ISSUE TITLE
Over hdmi has weird scaling issues and shimmering

### ISSUE THREAD

**Issue by Spazmoid1981** [MiSTer-devel/Arcade-SlapFight_MiSTer#2]
Looks like the resolution is wrong or the video processing over hdmi is not correctly sized - also adding any video filter results in some weird shimmering over the screen

**Comment by paulb-nl** [comment]
The `ce_pix` signal is generated incorrectly. Just output `pixel_clk` from slapcore.v and connect it directly to ce_pix and the `arcade_video` module will handle the rest.

https://github.com/MiSTer-devel/Arcade-SlapFight_MiSTer/blob/10bae8e3ea879105e4ef7865437a0482ff7a11ab/rtl/slapcore.v#L338

**Comment by antongale** [comment]
> The `ce_pix` signal is generated incorrectly. Just output `pixel_clk` from slapcore.v and connect it directly to ce_pix and the `arcade_video` module will handle the rest.
> 
> https://github.com/MiSTer-devel/Arcade-SlapFight_MiSTer/blob/10bae8e3ea879105e4ef7865437a0482ff7a11ab/rtl/slapcore.v#L338

Thank you for bringing this to my attention.  The core has been updated to bring the pixel_clk into arcade video.

**Comment by Spazmoid1981** [comment]
Thanks guys - awesome - happy new year to all

Regards,
Michael Johnson
07976400758

On 31 Dec 2022, at 18:58, Anton Gale ***@***.***> wrote:

﻿

Closed #2<https://github.com/MiSTer-devel/Arcade-SlapFight_MiSTer/issues/2> as completed.
