### ISSUE TITLE
unable to flip screen for Tate mode when using CCW Tate orientation

### ISSUE THREAD

**Issue by konradpop** [MiSTer-devel/Arcade-SlapFight_MiSTer#3]
flip screen option not available which is required when using a CCW tate screen

**Comment by capitaineflam25** [comment]
Thanks for pointing the issue, my CRT is also CCW

**Comment by antongale** [comment]
I am aware of the issue regarding the menu being missing.  An update will be released shortly.

**Comment by antongale** [comment]
A new update has been pushed,  Rotation is only available over HDMI.  If you wish to flip the screen on a CRT use the DIP switch INVERT option.
